site_name: AI KS
site_description: "Building AI powered knowledge stores"

repo_url: https://ai-knowledge-stores.netlify.app/
repo_name: RAG

theme:
  icon:
    repo: fontawesome/brands/github
  name: "material" # readthedocs
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: "purple"
      accent: "grey"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: "purple"
      accent: "white"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/Python-Test-Engineer/"

plugins:
  - search
  - mkdocstrings
  # - blog:
  #     blog_dir: blog
  #     blog_toc: true
  #     archive: true
  #     archive_name: All Articles
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - toc:
      permalink: true
      separator: "_"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

# Page tree
nav:
  - "Overview": "index.md"
  - "Knowledge Stores":
      - "Overview": "knowledge_stores/overview.md"
      - "Human example": "rag/human_example.md"
  - "RAG":
      - "Human example": "rag/human_example.md"
      - "RAG": "rag/rag.md"
      - "Graph RAG": "rag/graph_rag.md"
  - "AI Agents":
      - "What is an AI Agent?": "ai_agents/what_is_an_ai_agent.md"
      - "Frameworks": "ai_agents/frameworks.md"
  - "Architecture":
      - "Overview": "architecture/overview.md"
      - "Vector Store": "architecture/vector_store.md"
      - "Controller": "architecture/controller.md"
      - "Front end": "architecture/architecture.md"
      - "Deployment": "architecture/deployment.md"
  - "Evaluation":
      - "Overview": "evaluation/overview.md"
      - "Ragas": "evaluation/ragas.md"
      - "Giskard": "evaluation/giskard.md"
  - "Production":
      - "Overview": "production/overview.md"
  - "About Craig":
      - "Services": "craig/services.md"
      - "CV": "craig/cv.md"
      - "Courses": "craig/courses.md"
      - "Contact": "craig/contact.md"

copyright: |
  &copy; 2024 <a href="https://ai-knowledge-stores.netlify.app/"  target="_blank" rel="noopener">Craig West - Building AI powered knowledge Stores</a>
