site_name: AI Powered Knowledge Systems
site_description: "Building AI Powered knowledge Systems"

repo_url: https://ai-knowledge-systems.netlify.app/
repo_name: RAG

theme:
  icon:
    repo: fontawesome/brands/github
  name: "material" # readthedocs
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: "purple"
      accent: "grey"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: "purple"
      accent: "white"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/Python-Test-Engineer/"

plugins:
  - search
  - mkdocstrings
  # - blog:
  #     blog_dir: blog
  #     blog_toc: true
  #     archive: true
  #     archive_name: All Articles
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - toc:
      permalink: true
      separator: "_"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

# Page tree
nav:
  - "The Pitch": "index.md"
  - "RAG":
    - "What is RAG?": "rag/what_is_rag.md"
    - "Human example": "rag/human_example.md"
    - "Knowledge Stores": "rag/knowledge_stores.md"
    - "Graph RAG": "rag/graph_rag.md"
  - "AI Agents":
    - "What is an AI Agent?": "ai_agents/what_is_an_ai_agent.md"
    - "Frameworks": "ai_agents/frameworks.md"
  - "Pipeline":
      - "Gather": "pipeline/gather.md"
      - "Ingest": "pipeline/ingest.md"
      - "Pre-query": "pipeline/pre_query.md"
      - "Query": "pipeline/query.md"
      - "Rate with LLM": "pipeline/rate_with_llm.md"
      - "Generate": "pipeline/generate.md"
      - "User rate and cache": "pipeline/cache_and_rate.md"
      - "Prof Evaluation": "pipeline/prof_evaluate.md"
      - "Refine": "pipeline/refine.md"

  - "The Stack": "architecture.stack.md"

# performance in Pipeline
  # - "Performance":
  #     - "Overview": "evaluation/overview.md"
  #     - "Ragas": "evaluation/ragas.md"
  #     - "Giskard": "evaluation/giskard.md"
  - "About Craig":
      - "Services": "craig/services.md"
      - "CV": "craig/cv.md"
      - "Courses": "craig/courses.md"
      - "Contact": "craig/contact.md"

copyright: |
  &copy; 2024 <a href="https://ai-powered-knowledge-systems.netlify.app/"  target="_blank" rel="noopener">Craig West - Building AI Powered Knowledge Systems</a>
