site_name: AI Powered Knowledge Systems
site_description: "Building AI Powered knowledge Systems"

repo_url: https://ai-knowledge-systems.netlify.app/
repo_name: RAG

theme:
  icon:
    repo: fontawesome/brands/github
  name: "material" # readthedocs
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: "purple"
      accent: "grey"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: "purple"
      accent: "white"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/Python-Test-Engineer/"

plugins:
  - search
  - mkdocstrings
  # - blog:
  #     blog_dir: blog
  #     blog_toc: true
  #     archive: true
  #     archive_name: All Articles
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - toc:
      permalink: true
      separator: "_"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

# Page tree
nav:
  - "JK": "index.md"
  - "About": "more.md"
  - "Current Concepts": "current_concepts.md"
  - "Pipeline":
      - "Gather": "pipeline/01_gather.md"
      - "Ingest and NLP": "pipeline/02_ingest.md"
      - "Improve question": "pipeline/03_improve_question.md"
      - "Query": "pipeline/04_retrieve_docs.md"
      - "Rank and filter": "pipeline/05_rank_and_filter.md"
      - "Generate": "pipeline/06_generate.md"
      - "User rates and cache": "pipeline/07_user_rate_and_cache.md"
  - "Technical Concepts":
      - "Vector DBs": "concepts/vector_databases.md"
      - "Agents": "concepts/agents.md"
      - "Graph DB": "concepts/graph_db.md"
      - "Model Fine Tuning": "concepts/fine_tuning.md"
  - "Evaluation":
      - "Overview": "evaluation/overview.md"
      - "LLM as Judge": "evaluation/rate_with_llm.md"
      - "Domain Expert": "evaluation/domain_expert.md"
      - "Refine": "evaluation/refine.md"
  - "About Craig":
      - "Services": "craig/services.md"
      - "CV": "craig/cv.md"
      - "Courses": "craig/courses.md"
      - "Contact": "craig/contact.md"

copyright: |
  &copy; 2024 <a href="https://ai-powered-knowledge-systems.netlify.app/"  target="_blank" rel="noopener">Craig West - Building AI Powered Knowledge Systems</a>
